[project]
name = "ishara-e-shikkha"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tasrik0001", email = "tasrik0001@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "fastapi>=0.141.1",
    "openai-whisper>=20250625",
    "requests>=2.34.2",
    "uvicorn[standard]>=0.52.4",
]

[project.scripts]
ishara-e-shikkha = "ishara_e_shikkha:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.5",
]
